# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: pose1
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
    - r3f_palm_finger_1_joint
    - r3f_finger_1_joint_1
    - r3f_finger_1_joint_2
    - r3f_finger_1_joint_3
    - r3f_finger_1_joint_paradistal_hinge
    - r3f_finger_1_joint_median_actuating_hinge
    - r3f_finger_1_joint_median_actuating_hinge_median_bar
    - r3f_finger_1_joint_paramedian_hinge
    - r3f_finger_1_joint_paramedian_hinge_median_bar_underactuated
    - r3f_finger_1_joint_paraproximal_actuating_hinge
    - r3f_finger_1_joint_paraproximal_bar
    - r3f_finger_1_joint_proximal_actuating_hinge
    - r3f_finger_1_joint_proximal_actuating_bar
    - r3f_palm_finger_2_joint
    - r3f_finger_2_joint_1
    - r3f_finger_2_joint_2
    - r3f_finger_2_joint_3
    - r3f_finger_2_joint_paradistal_hinge
    - r3f_finger_2_joint_median_actuating_hinge
    - r3f_finger_2_joint_median_actuating_hinge_median_bar
    - r3f_finger_2_joint_paramedian_hinge
    - r3f_finger_2_joint_paramedian_hinge_median_bar_underactuated
    - r3f_finger_2_joint_paraproximal_actuating_hinge
    - r3f_finger_2_joint_paraproximal_bar
    - r3f_finger_2_joint_proximal_actuating_hinge
    - r3f_finger_2_joint_proximal_actuating_bar
    - r3f_palm_finger_middle_joint
    - r3f_finger_middle_joint_1
    - r3f_finger_middle_joint_2
    - r3f_finger_middle_joint_3
    - r3f_finger_middle_joint_paradistal_hinge
    - r3f_finger_middle_joint_median_actuating_hinge
    - r3f_finger_middle_joint_median_actuating_hinge_median_bar
    - r3f_finger_middle_joint_paramedian_hinge
    - r3f_finger_middle_joint_paramedian_hinge_median_bar_underactuated
    - r3f_finger_middle_joint_paraproximal_actuating_hinge
    - r3f_finger_middle_joint_paraproximal_bar
    - r3f_finger_middle_joint_proximal_actuating_hinge
    - r3f_finger_middle_joint_proximal_actuating_bar
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - r3f_palm_finger_1_joint
      - r3f_finger_1_joint_1
      - r3f_finger_1_joint_2
      - r3f_finger_1_joint_3
      - r3f_palm_finger_2_joint
      - r3f_finger_2_joint_1
      - r3f_finger_2_joint_2
      - r3f_finger_2_joint_3
      - r3f_palm_finger_middle_joint
      - r3f_finger_middle_joint_1
      - r3f_finger_middle_joint_2
      - r3f_finger_middle_joint_3
