# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: pose1
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
    - r3f_palm_finger_1_joint
    - r3f_finger_1_joint_1
    - r3f_finger_1_joint_2
    - r3f_finger_1_joint_3
    - r3f_finger_1_joint_paradistal_hinge
    - r3f_finger_1_joint_median_actuating_hinge
    - r3f_finger_1_joint_median_actuating_hinge_median_bar
    - r3f_finger_1_joint_paramedian_hinge
    - r3f_finger_1_joint_paramedian_hinge_median_bar_underactuated
    - r3f_finger_1_joint_paraproximal_actuating_hinge
    - r3f_finger_1_joint_paraproximal_bar
    - r3f_finger_1_joint_proximal_actuating_hinge
    - r3f_finger_1_joint_proximal_actuating_bar
    - r3f_palm_finger_2_joint
    - r3f_finger_2_joint_1
    - r3f_finger_2_joint_2
    - r3f_finger_2_joint_3
    - r3f_finger_2_joint_paradistal_hinge
    - r3f_finger_2_joint_median_actuating_hinge
    - r3f_finger_2_joint_median_actuating_hinge_median_bar
    - r3f_finger_2_joint_paramedian_hinge
    - r3f_finger_2_joint_paramedian_hinge_median_bar_underactuated
    - r3f_finger_2_joint_paraproximal_actuating_hinge
    - r3f_finger_2_joint_paraproximal_bar
    - r3f_finger_2_joint_proximal_actuating_hinge
    - r3f_finger_2_joint_proximal_actuating_bar
    - r3f_palm_finger_middle_joint
    - r3f_finger_middle_joint_1
    - r3f_finger_middle_joint_2
    - r3f_finger_middle_joint_3
    - r3f_finger_middle_joint_paradistal_hinge
    - r3f_finger_middle_joint_median_actuating_hinge
    - r3f_finger_middle_joint_median_actuating_hinge_median_bar
    - r3f_finger_middle_joint_paramedian_hinge
    - r3f_finger_middle_joint_paramedian_hinge_median_bar_underactuated
    - r3f_finger_middle_joint_paraproximal_actuating_hinge
    - r3f_finger_middle_joint_paraproximal_bar
    - r3f_finger_middle_joint_proximal_actuating_hinge
    - r3f_finger_middle_joint_proximal_actuating_bar
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - r3f_palm_finger_1_joint
      - r3f_finger_1_joint_1
      - r3f_finger_1_joint_2
      - r3f_finger_1_joint_3
      - r3f_palm_finger_2_joint
      - r3f_finger_2_joint_1
      - r3f_finger_2_joint_2
      - r3f_finger_2_joint_3
      - r3f_palm_finger_middle_joint
      - r3f_finger_middle_joint_1
      - r3f_finger_middle_joint_2
      - r3f_finger_middle_joint_3
arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  gains:
    shoulder_pan_joint: {p: 500000.0, i: 0.1, d: 0.0001}
    shoulder_lift_joint: {p: 500000.0, i: 0.1, d: 0.0001}
    elbow_joint: {p: 300.0, i: 0.1, d: 0.1}
    wrist_1_joint: {p: 300.0, i: 0.1, d: 0.1}
    wrist_2_joint: {p: 300.0, i: 0.1, d: 0.1}
    wrist_3_joint: {p: 300.0, i: 0.1, d: 0.1}
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - r3f_palm_finger_1_joint
    - r3f_finger_1_joint_1
    - r3f_finger_1_joint_2
    - r3f_finger_1_joint_3
    - r3f_palm_finger_2_joint
    - r3f_finger_2_joint_1
    - r3f_finger_2_joint_2
    - r3f_finger_2_joint_3
    - r3f_palm_finger_middle_joint
    - r3f_finger_middle_joint_1
    - r3f_finger_middle_joint_2
    - r3f_finger_middle_joint_3
  gains:
    r3f_palm_finger_1_joint: {p: 13.0, i: 0.0, d: 0.01}
    r3f_finger_1_joint_1: {p: 10.0, i: 0.0, d: 0.01}
    r3f_finger_1_joint_2: {p: 5.0, i: 0.0, d: 0.007}
    r3f_finger_1_joint_3: {p: 2.0, i: 0.0, d: 0.001}
    r3f_palm_finger_2_joint: {p: 13.0, i: 0.0, d: 0.01}
    r3f_finger_2_joint_1: {p: 10.0, i: 0.0, d: 0.01}
    r3f_finger_2_joint_2: {p: 5.0, i: 0.0, d: 0.007}
    r3f_finger_2_joint_3: {p: 2.0, i: 0.0, d: 0.001}
    r3f_palm_finger_middle_joint: {p: 13.0, i: 0.0, d: 0.01}
    r3f_finger_middle_joint_1: {p: 10.0, i: 0.0, d: 0.01}
    r3f_finger_middle_joint_2: {p: 5.0, i: 0.0, d: 0.007}
    r3f_finger_middle_joint_3: {p: 2.0, i: 0.0, d: 0.001}

gazebo_ros_control:
  pid_gains:
    r3f_palm_finger_1_joint: {p: 13.0, i: 0.0, d: 0.01}
    r3f_finger_1_joint_1: {p: 10.0, i: 0.0, d: 0.01}
    r3f_finger_1_joint_2: {p: 5.0, i: 0.0, d: 0.007}
    r3f_finger_1_joint_3: {p: 2.0, i: 0.0, d: 0.001}
    r3f_palm_finger_2_joint: {p: 13.0, i: 0.0, d: 0.01}
    r3f_finger_2_joint_1: {p: 10.0, i: 0.0, d: 0.01}
    r3f_finger_2_joint_2: {p: 5.0, i: 0.0, d: 0.007}
    r3f_finger_2_joint_3: {p: 2.0, i: 0.0, d: 0.001}
    r3f_palm_finger_middle_joint: {p: 13.0, i: 0.0, d: 0.01}
    r3f_finger_middle_joint_1: {p: 10.0, i: 0.0, d: 0.01}
    r3f_finger_middle_joint_2: {p: 5.0, i: 0.0, d: 0.007}
    r3f_finger_middle_joint_3: {p: 2.0, i: 0.0, d: 0.001}
    shoulder_pan_joint: {p: 500000.0, i: 0.1, d: 0.0001}
    shoulder_lift_joint: {p: 500000.0, i: 0.1, d: 0.0001}
    elbow_joint: {p: 300.0, i: 0.1, d: 0.1}
    wrist_1_joint: {p: 300.0, i: 0.1, d: 0.1}
    wrist_2_joint: {p: 300.0, i: 0.1, d: 0.1}
    wrist_3_joint: {p: 300.0, i: 0.1, d: 0.1}


